### ISSUE TITLE
macOS incompatible 

### ISSUE THREAD

**Issue by euf** [neutronscott/bash-totp#2]
Hi, this is a nice project! Unfortunately I have a bunch of errors when run it on macOS 10.14.6 (shipped with /bin/bash version 3.2.57). 

```
./totp.sh: line 273: ${c^^}*: bad substitution
./totp.sh: line 256: printf: `(': invalid format character
          google   328482
./totp.sh: line 273: ${c^^}*: bad substitution
./totp.sh: line 256: printf: `(': invalid format character
        facebook   328482
./totp.sh: line 273: ${c^^}*: bad substitution
./totp.sh: line 256: printf: `(': invalid format character
          github   328482
(A)dd (D)el (S)ave (L)oad (T)est (X)XTEA (Q)uit:
```

**Comment by neutronscott** [comment]
The errors shown here could be fixed by replacing the lines with a pipe to `tr` to change case. But there's likely more bash4+ features in there. Just isn't worth targeting old bash.

Many scripts won't because bash3 is ancient. Perhaps zsh will work or a recent bash from homebrew. You'll then need to change the first line to point to where homebrew puts it's copy of bash.

**Comment by neutronscott** [comment]
Try the changes in commit 0ad79431c999faaaafc97fc6bd9474d30ba9c790
